Admin System
AmperSoftware/TF-Source-2 pull request #75
Opened 2023-02-10 00:34 UTC by qualitykk

# Adds a Moderation and Server Management System to tfs2
- Adds Whitelists
- Adds Reserved Slots
- Adds Permission System
- Adds Kick, Ban, Slay, Slap and much more

2023-02-10 09:17 UTC, Retr0-01 requested changes
Besides my comments, I have not managed to test the admin system fully.
None of the commands work (both internal provided by the system and the converted gamemode-specific ones). They do not show up on autocomplete, they basically do not exist.

2023-02-10 09:17 UTC, Retr0-01 commented on code/Libraries/Admin/BreakerEvent.cs
> +					Event.Run( "Breaker.player.joined", client );
Will this (and every other `Event.Run()`) work considering the first letter of the event does not match the registered one? Also, wouldn't it be wise to declare some constant strings to store the event names?

2023-02-10 11:36 UTC, qualitykk commented on code/Libraries/Admin/BreakerEvent.cs
> +					Event.Run( "Breaker.player.joined", client );
It has worked so far but its now a constant string.

2023-02-10 11:37 UTC, qualitykk commented on code/Libraries/Admin/BreakerEvent.cs
> +			public PlayerNumberChangedAttribute() : base( "breaker.players.changed" ) { }
We dont need it anymore, so its removed and replaced with hooking to both leaving and joining events.

2023-02-10 11:40 UTC, qualitykk commented
> Besides my comments, I have not managed to test the admin system fully. None of the commands work (both internal provided by the system and the converted gamemode-specific ones). They do not show up on autocomplete, they basically do not exist.

You use the commands by using the command of the admin system + the actual command you wanna use
So for example slapping everybody would be `brk slap @all 500`
I didnt want it to be that way but thats the only way you can stop the commands before they are actually executed.
I should probably have specified that in the PR now that i think about it :/

2023-02-10 17:53 UTC, Retr0-01 approved these changes

2023-02-11 23:16 UTC, rob5300 requested changes

2023-02-11 23:16 UTC, rob5300 commented on code/Libraries/Admin/Commands/Command.cs
> +				throw new ArgumentNullException( "name" );
Arg should be `"key"` or `nameof(key)` ?

2023-02-11 23:16 UTC, rob5300 commented on code/Libraries/Admin/Commands/Moderation.cs
> +			public float Duration { get; set; }
Id advice using MS for `Duration` as that is what DateTime will be using (unix time) and means time is a consistent format.

2023-02-11 23:16 UTC, rob5300 commented on code/Libraries/Admin/Commands/Moderation.cs
> +					return $"{time.TotalSeconds}s";
I think `TimeSpan` has `ToString()` customizable formatting that can do this better.

2023-02-11 23:16 UTC, rob5300 commented on code/Libraries/Admin/Commands/Parsers/ClientParser.cs
> +		private static IClient SelectRandom( IClient caller, string arg ) => Game.Clients.OrderBy( cl => Guid.NewGuid() ).FirstOrDefault();
More efficient to select by random number in 0 -> Length range

2023-02-12 12:52 UTC, qualitykk commented on code/Libraries/Admin/Attributes.cs
> +		public static IEnumerable<MethodDescription> FindMethods<T>() where T : Attribute
I switched everything from IEnumerable to Arrays since the data doesnt need to be modified after you get it

2023-02-12 12:57 UTC, qualitykk commented on code/Libraries/Admin/Commands/Moderation.cs
> +			public float Duration { get; set; }
Im not using MS here since you dont need that much precision with bans since usually even the shortest bans are in the minute range, if you still think it should still use MS with that use case then ill switch it.

2023-02-12 21:10 UTC, rob5300 requested changes

2023-02-12 21:10 UTC, rob5300 commented on code/Libraries/Admin/Commands/Moderation.cs
> +				int miliseconds = duration.Seconds;
Incorrect name

2023-02-12 21:10 UTC, rob5300 commented on code/Libraries/Admin/Commands/Parsers/ClientParser.cs
> +		private static IClient SelectRandom( IClient caller, string arg ) => Game.Clients.OrderBy( cl => Game.Random.Int(0, Game.Clients.Count) ).FirstOrDefault();
`Game.Clients[Game.Random.Int(0, Game.Clients.Count)]` or `Game.Clients.ElementAt(Game.Random.Int(0, Game.Clients.Count))`

Not sure why you kept the Ordering

2023-02-12 22:31 UTC, rob5300 approved these changes

2023-02-13 16:59 UTC, merged