Taunt System
AmperSoftware/TF-Source-2 pull request #84
Opened 2023-03-08 09:39 UTC by Retr0-01

This PR implements the taunt system.
- Press "G" to show the taunt menu.
- Double press "G" quickly to taunt using your currently equipped weapon.
- Default taunt support.
- Partner taunts support.
- Moving taunt support.

2023-03-08 22:02 UTC, rob5300 requested changes

2023-03-08 22:02 UTC, rob5300 commented on code/UI/TauntMenu.cs
> +			Add.Button( taunt.DisplayName, "button", () => ConsoleSystem.Run( "tf_playtaunt", taunt.ResourceName ) );
Verify that taunt gets correctly captured to be the value per loop run.

2023-03-08 22:02 UTC, rob5300 commented
Unsure if we need all those `if ( Game.LocalPawn is not TFPlayer player ) return;` checks but we can discuss it.

2023-03-09 09:08 UTC, N-cognito commented on code/Player/Data/TauntData.cs
> +				taunt = taunt_data;
Can do, had to make a second return null if we have a string that doesn't match any given taunts

2023-03-09 09:09 UTC, N-cognito commented on code/UI/TauntMenu.cs
> +			Add.Button( taunt.DisplayName, "button", () => ConsoleSystem.Run( "tf_playtaunt", taunt.ResourceName ) );
Fixed this in previous commit, but forgot to remove this note I left for myself

2023-03-09 15:29 UTC, qualitykk approved these changes

2023-03-09 15:29 UTC, qualitykk commented on code/Player/Taunts.cs
> +	/* //Disabled, yandere-dev moment, need to find a better way to relay class-dependent durations or need to squash them
Might wanna remove this big comment block if this code has already been remade

2023-03-11 19:40 UTC, rob5300 approved these changes

2023-03-12 11:21 UTC, merged